[project]
name = "aws-services-regions"
version = "0.1.0"
description = "Fast MCP server that helps LLMs to optimally and accurately find list of all AWS services available in AWS regions."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.12.0",
    "bs4>=0.0.2"
]
